### ISSUE TITLE
Feature Request: override current language manually

### ISSUE THREAD

**Issue by omar84** [jeresig/i18n-node-2#109]
First, thanks for the great work you've done here..

I'd like to be able to override the current language, to show a translation of the phrase I want to use.

it could be something like:

languages = ['en', 'fr'];
// assuming the default language is 'en'
console.log( req.i18n.__('global.language') ); //prints: English
console.log( req.i18n.__o('fr', 'global.language') ); //prints: Français

Can this be done? and how soon? 
Thanks.

**Comment by gjuchault** [comment]
https://github.com/jeresig/i18n-node-2/blob/master/i18n.js#L153

You might want to try using `translate` directly

**Comment by omar84** [comment]
Worked perfectly.. thanks :)
