### ISSUE TITLE
how to use for ejs template?

### ISSUE THREAD

**Issue by marti1125** [jeresig/i18n-node-2#11]
exports.index = function(req, res){
  res.render('index', { title: 'Welcome' , slides: req.i18n.__('slides') });
};
&lt;h2&gt;&lt;%= slides %&gt;&lt;/h2&gt;

 "express": "3.1.0"

I get this error 500 TypeError: Cannot call method '__' of undefined

**Comment by gtrabanco** [comment]
Why closed? It is not resolved.

**Comment by gjuchault** [comment]
It's closed because the solution was given : there was a missing `i18n.expressBind()` which must be called. See https://github.com/jeresig/i18n-node-2#using-with-expressjs for more informations
