### ISSUE TITLE
i18n should be silent by default

### ISSUE THREAD

**Issue by e-compton** [jeresig/i18n-node-2#113]
https://github.com/jeresig/i18n-node-2/blob/34bb8950e5af6ccbb31f2be8f10ee487e4c70ab8/i18n.js#L192

Hi, I noticed you're printing directly to the console when in devMode. This can cause spam for those working with the module.

It might be a better idea to use [debug](https://www.npmjs.com/package/debug), it will only print when the `DEBUG` environment variable is set to a particular value. This was also used in the previous [i18n](https://github.com/mashpie/i18n-node).

**Comment by gjuchault** [comment]
Hi,

Having not so much time these days, while I totally agree on the fact that we should use debug or some proper logging function, I can't implement it; but I'd merge a PR for sure ;)

Thanks

**Comment by e-compton** [comment]
Awesome, I've made the changes sent a [pull request](https://github.com/jeresig/i18n-node-2/pull/114)
