### ISSUE TITLE
The sprintf package is deprecated in favor of sprintf-js

### ISSUE THREAD

**Issue by hbakhtiyor** [jeresig/i18n-node-2#120]

**Comment by avallete** [comment]
The title is pretty explicit.

Did we have any update on this issue ?

PS: I mention as an additional intel that the `sprintf-js` package does not seem to make any breaking change (I've checked all the releases and searched for 'migration guides'). So the update should be straight forward.

Plus, a PR is already waiting to be merged to address this issue: https://github.com/jeresig/i18n-node-2/pull/122

@gjuchault could you please check and merge this PR ?

**Comment by gjuchault** [comment]
@avallete I just saw the PR and merged it thanks :)
