### ISSUE TITLE
Auto-detect supported locales from locales directory?

### ISSUE THREAD

**Issue by aseemk** [jeresig/i18n-node-2#22]
It would be great if I didn't have to specify the locales manually, if instead it could just be derived automatically by seeing which `extension` (e.g. `.js`) files were in `directory` (e.g. `./locales`).

That way, you wouldn't need to maintain the list of locales in the configuration separately from the files you've had translated.

Would you be open to that? I might be able to put together a pull req if so. Thanks again for the great lib!

**Comment by gjuchault** [comment]
Closed (the comment answers the issue)
