### ISSUE TITLE
readFile error checking

### ISSUE THREAD

**Issue by ryleyb** [jeresig/i18n-node-2#35]
While deploying my express 3.X app the first time to production, I ran into an issue with readFile where it wasn't able to read the locales directory, and also didn't have permissions to write new files.  Relevant code from i18n.js (https://github.com/jeresig/i18n-node-2/blob/master/i18n.js#L268):

```javascript
try {
    var localeFile = fs.readFileSync(file);
    //... continues
} catch (e) {
    this.writeFile(locale);
}
```

The end result is that my app complains that it can't find `res.locals.__`.  Which makes sense - the middleware for express in `expressBind` calls `new i18n(opts)` which isn't successful, and thus (silently AFAIK) dies.

I think a reasonable thing to do might be to wrap the writeFile call in a try/catch and log an error.  I can create a PR if that seems reasonable to you.

(PS: I'm not asking for help with my app - I just needed to explicitly pass the `directory` option)

**Comment by gjuchault** [comment]
> I can create a PR if that seems reasonable to you.

Please do :smile:

**Comment by gjuchault** [comment]
I think https://github.com/jeresig/i18n-node-2/issues/39 closes this issue ?
