### ISSUE TITLE
Using i18n-2 in models

### ISSUE THREAD

**Issue by pierissimo** [jeresig/i18n-node-2#60]
Hi!

I would to use i18n-2 in models js files, during data valitation.
How to access i18n2 functions?

I tried with

```
var i18n = require('i18n-2');

var validationError = i18n.__("Validation error");
```

but i get "i18n.__("Validation error")
                  ^
TypeError: undefined is not a function"

What am i doing wrong?

Thanks

**Comment by gjuchault** [comment]
Hi !

You must instanciate i18n before. Check the examples in the Readme !

**Comment by pierissimo** [comment]
Ok, i thought that use expressBind was enough.
Thank you
