### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by bbqsrc** [jeresig/i18n-node-2#67]
The [mashpie/i18n-node](https://github.com/mashpie/i18n-node) base project is MIT, but no license is found in this repo, nor even referred to in the `package.json`.

Can this be rectified? I can't use this in my projects without a permissive license, and certainly, no license is not permissive. :smile:

**Comment by gjuchault** [comment]
No license is Public Domain !
Maybe @jeresig can add a license (I won't add a license for him)

**Comment by bbqsrc** [comment]
I understand that may be the intention @gjuchault but that is unfortunately not how copyright works by default, which is 'no license = public domain'. Unfortunately, it's more like 'no license = all rights reserved, see you in court'.

This is how international copyright law is organised. Unless you explicitly declare your work into the public domain such as through the [Creative Commons Zero license](https://creativecommons.org/publicdomain/zero/1.0/), all rights remain reserved (except those foregone due to the GitHub terms and conditions, which merely grants viewing and forking rights, but goes into no more detail).

Also, as this is a fork, it is a derivative work. This means that any licensing requirements specified in the original codebase have to be followed, which usually at the very least includes a requirement for attribution. If it isn't followed, it is considered copyright infringement as the attribution is not being made and the license not being followed.

One can see that the repository now uses an MIT license, so dragging in the LICENSE file and attribution of the original author should be enough to resolve this issue, as the MIT license is effectively public domain with an attribution requirement anyway. :smile:

**Comment by bbqsrc** [comment]
Oh, I just noticed that MIT is actually the license! It's referred to only in the header of the i18n.js file.

I might make a pull request that adds the MIT license to the repo, meets attribution requirements and adds the correct property to the package.json. :+1:

**Comment by bbqsrc** [comment]
I have created #68 for this. Thanks @gjuchault :smiley:
