### ISSUE TITLE
__n() treats zero as singular

### ISSUE THREAD

**Issue by shabushabu** [jeresig/i18n-node-2#71]
Given that we have the following function:

```javascript
i18n.__n('%s movie', '%s movies', 0);
```

We get `0 movie` back. Surely, this should be `0 movies`? Is there a specific reason for this behaviour?

Cheers!

**Comment by gjuchault** [comment]
In fact; it depends a lot of the language. In English; 0 is considered plural; in French not, and so on.

**Comment by gjuchault** [comment]
Actually we'll see how https://github.com/jeresig/i18n-node-2/issues/78 resolves
