### ISSUE TITLE
release 0.4.7 on npmjs.com

### ISSUE THREAD

**Issue by lubomir-haralampiev** [jeresig/i18n-node-2#72]
Hi,

I'd like to use the latest version 0.4.7 which implements the dot notation for the translation keys.

Please update the release on npmjs.com

Cheers

**Comment by gjuchault** [comment]
Only @jeresig can do that (it'd be great if there was an automatic publishing service - TravisCI to do that)

**Comment by Joshua-F** [comment]
+1 would love to use dot notation

ping @jeresig or @KLicheR

**Comment by jeresig** [comment]
@gjuchault what is your npm username? I can give you access to push releases.

**Comment by gjuchault** [comment]
Same (`gjuchault`)

**Comment by joshzume** [comment]
Is there an ETA for npm version to be updated?

**Comment by jeresig** [comment]
Sorry for the delay. I've just given @gjuchault access to the npm module, he should be able to publish now.

**Comment by joshzume** [comment]
awesome

**Comment by gjuchault** [comment]
In fact; there is some problems with the dot notation (if you try to translate a real sentence that contains a dot - as in the tests -) they don't pass as they're treated as object paths. How should we reat that

**Comment by gjuchault** [comment]
Version 0.6.0 has been published
