### ISSUE TITLE
i18n-node-2 for Hapi

### ISSUE THREAD

**Issue by andrezzoid** [jeresig/i18n-node-2#73]
Hey folks,

I've read both @jeresig posts about his i18n strategy ([here](http://ejohn.org/blog/a-strategy-for-i18n-and-node/) and [here](http://ejohn.org/blog/i18n-module-for-node-and-express-js/)) and I like what you've accomplished here. The thing is, I use [Hapi](http://hapijs.com) instead of Express. Since this module is MIT licenced, I'm letting you know that I'm going to adapt it to work with Hapi and launch it as a plugin. Hope that's ok.

**Comment by jeresig** [comment]
That's great - go ahead!

--John
