### ISSUE TITLE
nested objects does not work

### ISSUE THREAD

**Issue by ersensen** [jeresig/i18n-node-2#76]
From the documentation the following code does not work.

{
    'foo': {
        'bar': 'ok'
    }
}

i18n.__('foo.bar');

**Comment by gregpardo** [comment]
I have this problem also. It basically adds a key 'foo.bar' to the bottom.

**Comment by gjuchault** [comment]
Hello,

First of all; you may describe a little more your problem and the context : what version do you use, are you in debug mode or not, etc.

I'm guessing you're installing from NPM so the version you have is not up to date (and this is being fixed : https://github.com/jeresig/i18n-node-2/issues/74)

**Comment by gjuchault** [comment]
See #72
