### ISSUE TITLE
New strings not saved

### ISSUE THREAD

**Issue by abdelilah** [jeresig/i18n-node-2#82]
Hello,

As in the title, new strings are not saved to locales file in version 0.6.0

I added a quick fix in after line 329 like this:

if (!this.locales[locale][singular]) {
  this.locales[locale][singular] = singular; // the fix
  if (this.devMode) {
    this.writeFile(locale);
  }
}

Hope this will be fixed soon

**Comment by gjuchault** [comment]
Could you make a PR for this ? And add some tests with your use case

**Comment by gjuchault** [comment]
Closed by #83
