### ISSUE TITLE
release schedule for 0.4.8 ?

### ISSUE THREAD

**Issue by k2s** [jeresig/i18n-node-2#89]
please, could you release new version where at least this fix https://github.com/jeresig/i18n-node-2/commit/b99fd69469d0f014c1a2015800aa206d8ed23998 would be included ?

**Comment by gjuchault** [comment]
https://www.npmjs.com/package/i18n-2

Actually, 0.4.8 was released some times ago. You may speak about 0.6.3 then. I forgot to publish, which is done now !
