### ISSUE TITLE
HTML character entities are not handled properly

### ISSUE THREAD

**Issue by kdidenko** [jeresig/i18n-node-2#95]
When using HTML character entities they are not displayed properly. For example:
`#{__("&mdash; or &mdash;")}`
is translated to:
`&amp;mdash; or &amp;mdash;`

Is there any way to escape `&` so it will be converted to `&amp;`? Then everything should work fine.
It is very strange that only `&` is converted since when I'm using `#{__("— or —")}` the `—` entity is not converted to `&mdash;` and is rendered in html as is.

**Comment by gjuchault** [comment]
Why don't you use UTF-8 files ?

**Comment by SamBellerose** [comment]
@gjuchault Can you give more details on how I can use HTML in my json files ? I understand the UTF-8 files format, but how can I achieve this? Is there a config in i18n-2?

**Comment by gjuchault** [comment]
@SamBellerose You can use UTF-8 files directly and avoid thinking about encoding and HTML chars. Let's say you want the mdash character (—).
Instead of

```
{ "foo": "&mdash;" }
```

Use
```
{ "foo": "—" }
```
